server:
  error:
    include-message: always
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: postgres://yldqlwlylwnfhf:a8173723553798df8b959576a8037a94b3ea799351c40dc74d20e2f87e84d018@ec2-3-225-213-67.compute-1.amazonaws.com:5432/dem2idqjecippu

    username: yldqlwlylwnfhf
    driver-class-name:
    password: a8173723553798df8b959576a8037a94b3ea799351c40dc74d20e2f87e84d018

  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000
debug: true
