server:
  error:
    include-message: always
  port: 5603
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: postgresql://postgres:pmN8g2no4pzDVlRbEYv7@containers-us-west-180.railway.app:5603/railway
    username: postgres
    driver-class-name:
    password: pmN8g2no4pzDVlRbEYv7
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000
debug: true
