server:
  error:
    include-message: always
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: postgres://dlidobriy:h3JDA08wlXnqPmJ8m0A39dCZPspVBjgs@dpg-cmihfnud3nmc73cjg200-a/dlidobriy_zt92

    username: dlidobriy
    driver-class-name: org.postgresql.Driver
    password: h3JDA08wlXnqPmJ8m0A39dCZPspVBjgs

  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000
debug: true
