server:
  error:
    include-message: always
#  port: 8080
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}
    password: pmN8g2no4pzDVlRbEYv7


#    url: jdbc:postgresql://localhost:5432/book_api
    username: postgres
#    password: root
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000

