server:
  error:
    include-message: always
#  port: 8080
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ismajjsbdwpbwv:5b43fe7ed37202a1e8b1c4ed72527338eca8202ed07ba7e432a828acfde48a54@ec2-44-207-126-176.compute-1.amazonaws.com:5432/ddaa5vmsks3taj
    password: 5b43fe7ed37202a1e8b1c4ed72527338eca8202ed07ba7e432a828acfde48a54
    username: ismajjsbdwpbwv

#    url: jdbc:postgresql://localhost:5432/book_api
#    username: postgres
#    password: root
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000

