server:
  error:
    include-message: always
#  port: 8080
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://lpmelpxkeikazw:0cb4c4e6147fcb36103ce0c2c5d0d0fe0fab85dd6199dd7bff48fb725fcd65d8@ec2-52-204-195-41.compute-1.amazonaws.com:5432/df0tlusd7dje1l
    password: 0cb4c4e6147fcb36103ce0c2c5d0d0fe0fab85dd6199dd7bff48fb725fcd65d8
    username: lpmelpxkeikazw

#    url: jdbc:postgresql://localhost:5432/book_api
#    username: postgres
#    password: root
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /apidoc



jwt:
  secretKey: dlidobriy
  expireTime: 864000000

