server:
#  port: 80
  port: 5432
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/school_book
    url: ec2-3-219-229-143.compute-1.amazonaws.com
#    username: postgres
#    password: root
    username: mvbsllbykekfya
    password: da868d1a28abeb16660bc0ba43018f199edacae11c974a87ff434e9c0414ced1
  sql:
    init:
      mode: always
  mvc:
    servlet:
      path: /api
  servlet:
    multipart:
      max-file-size: 10MB


jwt:
  secretKey: dlidobriy
  expireTime: 864000000
